language: php
sudo: required
services: docker
php: 5.6
before_script:
  - docker network create beholder-network
  - docker-compose up -d
script:
  - codecept run nfs
cache:
  directories:
  - vendor
