language: php
sudo: required
services: docker
php: 5.6
before_script:
  - docker network create beholder-network
  - docker-compose build
  - docker-compose up -d
  - tests/mysql/travis.sh
  - tests/postgresql/travis.sh
  - composer install
  - tests/mysql/migrate.sh
script:
  - docker exec -it beholder-web-client bash -c 'vendor/bin/codecept run --coverage --coverage-xml || exit $?'
after_success:
  - bash <(curl -s https://codecov.io/bash) -s ./tests/_output
