language: php
sudo: required
services: docker
php: 5.6
before_script:
  - docker network create beholder-network
  - docker-compose build
  - docker-compose up -d
  - composer install
script:
  - vendor/bin/codecept run url
